AquaZooWeb/Models/AquaZooEntity.cs
using System.ComponentModel.DataAnnotations;

namespace AquaZooWeb.Models
{
    public class AquaZooEntity
    {

        public int AquaZooId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string PropertyType { get; set; }

        [Required]
        public string State { get; set; }

        public DateTime Created { get; set; }

        public DateTime Started { get; set; }
    }
}

AquaZooWeb/Models/ErrorViewModel.cs
namespace AquaZooWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AquaZooWeb/Models/LocationProgramEntity.cs
using System.ComponentModel.DataAnnotations;

namespace AquaZooWeb.Models
{
    public class LocationProgramEntity
    {

        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string AgeGroup { get; set; }

        [Required]
        public double Price { get; set; }

        [Required]
        public int AquaZooId { get; set; }


        public AquaZooEntity AquaZooEntity { get; set; }
    }
}

AquaZooWeb/Models/User.cs
namespace AquaZooWeb.Models
{
    public class User
    {
         
        public string Username { get; set; }
        public string Password { get; set; }

        public string Role { get; set; }

        
        public string Token { get; set; }
    }
}

AquaZooWeb/Controllers/AquaZooController.cs
using AquaZooWeb.UIRepository;
using Microsoft.AspNetCore.Mvc;

namespace AquaZooWeb.Controllers
{
    public class AquaZooController : Controller
    {
        private readonly IAquaZooRepository _repo;

        public AquaZooController( IAquaZooRepository aquaZooRepository)
        {
            _repo = aquaZooRepository; 
        }
        public IActionResult Index2()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {

            return Json( new {  data = await _repo.GetAllAsync (WebUtility.APIAquaZooPath, HttpContext.Session.GetString(WebUtility.TokenName) )
            });

        }
    }
}

AquaZooWeb/Controllers/HomeController.cs
using AquaZooWeb.Models;
using AquaZooWeb.UIRepository;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AquaZooWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IAccountRepository _accountRepository;

        public HomeController(ILogger<HomeController> logger, IAccountRepository accountRepository)
        {
            _logger = logger;
            _accountRepository = accountRepository; 
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            User obj = new User();
            return View(obj );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(User Obj )
        {
            User obj = await _accountRepository.LoginAsync(WebUtility.APIAccountPath + "/Authenticate", Obj); 

            if ( obj.Token == null)
            {
                return View(); 
            }

            HttpContext.Session.SetString( WebUtility.TokenName , obj.Token);
            return RedirectToAction("Index"); 

            
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(User Obj)
        {
            bool result = await _accountRepository.RegisterAsync(WebUtility.APIAccountPath + "/Register", Obj);

            if ( result  == false )
            {
                return View();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(User Obj)
        {
            HttpContext.Session.SetString( WebUtility.TokenName ,"");

            return RedirectToAction("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AquaZooWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to world of Aquarium and zoo v2 !!</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AquaZooWeb/Views/Home/Login.cshtml
@model AquaZooWeb.Models.User

<h1>Login</h1>
<form method="post">
    <input asp-for="Username" type="text" placeholder="Username..." />
    <input asp-for="Password" type="text" placeholder="Password..." />
    <button type="submit" value="Submit">Login</button>

</form>

AquaZooWeb/Views/Home/Register.cshtml
@model AquaZooWeb.Models.User

<h1>Register</h1>
<form method="post">
    <input asp-for="Username" type="text" placeholder="Username..." />
    <input asp-for="Password" type="text" placeholder="Password..." />
    <button type="submit" value="Submit">Register</button>

</form>

AquaZooWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpAcc

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AquaZooWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AquaZooWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AquaZooWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if( httpAcc.HttpContext.Session.GetString(WebUtility.TokenName) != null &&  httpAcc.HttpContext.Session.GetString(WebUtility.TokenName).Length > 0 )
                        {
                            //show menu
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AquaZoo" asp-action="Index">Aquazium</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }else
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Register</a>
                        </li>
                            
                        }

                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AquaZooWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>